/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as DanhGiaRouteImport } from './routes/danh-gia'
import { Route as DieuHanhRouteImport } from './routes/dieu-hanh'
import { Route as DoiRouteImport } from './routes/doi'
import { Route as GiaiDieuRouteImport } from './routes/giai-dieu'
import { Route as HoSoRouteImport } from './routes/ho-so'
import { Route as Kt338RouteImport } from './routes/kt338'
import { Route as LichRouteImport } from './routes/lich'
import { Route as PhanHoiRouteImport } from './routes/phan-hoi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhGiaRoute = DanhGiaRouteImport.update({
  id: '/danh-gia',
  path: '/danh-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuHanhRoute = DieuHanhRouteImport.update({
  id: '/dieu-hanh',
  path: '/dieu-hanh',
  getParentRoute: () => rootRouteImport,
} as any)
const DoiRoute = DoiRouteImport.update({
  id: '/doi',
  path: '/doi',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaiDieuRoute = GiaiDieuRouteImport.update({
  id: '/giai-dieu',
  path: '/giai-dieu',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoRoute = HoSoRouteImport.update({
  id: '/ho-so',
  path: '/ho-so',
  getParentRoute: () => rootRouteImport,
} as any)
const Kt338Route = Kt338RouteImport.update({
  id: '/kt338',
  path: '/kt338',
  getParentRoute: () => rootRouteImport,
} as any)
const LichRoute = LichRouteImport.update({
  id: '/lich',
  path: '/lich',
  getParentRoute: () => rootRouteImport,
} as any)
const PhanHoiRoute = PhanHoiRouteImport.update({
  id: '/phan-hoi',
  path: '/phan-hoi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/danh-gia': typeof DanhGiaRoute
  '/dieu-hanh': typeof DieuHanhRoute
  '/doi': typeof DoiRoute
  '/giai-dieu': typeof GiaiDieuRoute
  '/ho-so': typeof HoSoRoute
  '/kt338': typeof Kt338Route
  '/lich': typeof LichRoute
  '/phan-hoi': typeof PhanHoiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/danh-gia': typeof DanhGiaRoute
  '/dieu-hanh': typeof DieuHanhRoute
  '/doi': typeof DoiRoute
  '/giai-dieu': typeof GiaiDieuRoute
  '/ho-so': typeof HoSoRoute
  '/kt338': typeof Kt338Route
  '/lich': typeof LichRoute
  '/phan-hoi': typeof PhanHoiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/danh-gia': typeof DanhGiaRoute
  '/dieu-hanh': typeof DieuHanhRoute
  '/doi': typeof DoiRoute
  '/giai-dieu': typeof GiaiDieuRoute
  '/ho-so': typeof HoSoRoute
  '/kt338': typeof Kt338Route
  '/lich': typeof LichRoute
  '/phan-hoi': typeof PhanHoiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/danh-gia'
    | '/dieu-hanh'
    | '/doi'
    | '/giai-dieu'
    | '/ho-so'
    | '/kt338'
    | '/lich'
    | '/phan-hoi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/danh-gia'
    | '/dieu-hanh'
    | '/doi'
    | '/giai-dieu'
    | '/ho-so'
    | '/kt338'
    | '/lich'
    | '/phan-hoi'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/danh-gia'
    | '/dieu-hanh'
    | '/doi'
    | '/giai-dieu'
    | '/ho-so'
    | '/kt338'
    | '/lich'
    | '/phan-hoi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  DanhGiaRoute: typeof DanhGiaRoute
  DieuHanhRoute: typeof DieuHanhRoute
  DoiRoute: typeof DoiRoute
  GiaiDieuRoute: typeof GiaiDieuRoute
  HoSoRoute: typeof HoSoRoute
  Kt338Route: typeof Kt338Route
  LichRoute: typeof LichRoute
  PhanHoiRoute: typeof PhanHoiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-gia': {
      id: '/danh-gia'
      path: '/danh-gia'
      fullPath: '/danh-gia'
      preLoaderRoute: typeof DanhGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-hanh': {
      id: '/dieu-hanh'
      path: '/dieu-hanh'
      fullPath: '/dieu-hanh'
      preLoaderRoute: typeof DieuHanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doi': {
      id: '/doi'
      path: '/doi'
      fullPath: '/doi'
      preLoaderRoute: typeof DoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giai-dieu': {
      id: '/giai-dieu'
      path: '/giai-dieu'
      fullPath: '/giai-dieu'
      preLoaderRoute: typeof GiaiDieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so': {
      id: '/ho-so'
      path: '/ho-so'
      fullPath: '/ho-so'
      preLoaderRoute: typeof HoSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kt338': {
      id: '/kt338'
      path: '/kt338'
      fullPath: '/kt338'
      preLoaderRoute: typeof Kt338RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich': {
      id: '/lich'
      path: '/lich'
      fullPath: '/lich'
      preLoaderRoute: typeof LichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phan-hoi': {
      id: '/phan-hoi'
      path: '/phan-hoi'
      fullPath: '/phan-hoi'
      preLoaderRoute: typeof PhanHoiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  DanhGiaRoute: DanhGiaRoute,
  DieuHanhRoute: DieuHanhRoute,
  DoiRoute: DoiRoute,
  GiaiDieuRoute: GiaiDieuRoute,
  HoSoRoute: HoSoRoute,
  Kt338Route: Kt338Route,
  LichRoute: LichRoute,
  PhanHoiRoute: PhanHoiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
